speedtest: fix Erdos2 test
First bug in Erdos2.java

    java.lang.Exception: Method test should have no parameters

Second bug in Erdos.java

    java.lang.IllegalArgumentException: Invalid Schema: column names
    must be unique.

Note that second bug was caused by my changing the way that LocalJoin
handles column names in #249