MyriaApiException: passthrough Myria API Exceptions
If for some reason we pass a `MyriaApiException` as the `cause` to
`MyriaApiException`, simply pass its `Response` through.

Signed-off-by: Daniel Halperin <dhalperi@cs.washington.edu>