ConstantEvaluator: better error message
If possible, we should print the Java that causes the failure. Before
this change:

edu.washington.escience.myria.DbException: Error when evaluating expression edu.washington.escience.myria.expression.evaluate.ConstantEvaluator@48dd0a33

After:

edu.washington.escience.myria.DbException: Error when evaluating expression (1/0)