MyriaApiException: create new RuntimeException to wrap cause for Java
The current method was conveying the response to the user, but was not
keeping the explanation in the throwable itself for presentation in
Java exception toString() functions.